Update Jenkinsfile

diff --git a/gateway/Jenkinsfile b/gateway/Jenkinsfile
--- a/gateway/Jenkinsfile
+++ b/gateway/Jenkinsfile
@@ -33,6 +33,36 @@ pipeline{
             }
         }
 
+        stages {
+            stage('Install Docker') {
+                steps {
+                    script {
+                        sh '''
+                        if ! command -v docker &> /dev/null
+                        then
+                            echo "Docker could not be found, installing Docker..."
+                            sudo apt-get update
+                            sudo apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common
+                            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
+                            sudo add-apt-repository \
+                               "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
+                               $(lsb_release -cs) \
+                               stable"
+                            sudo apt-get update
+                            sudo apt-get install -y docker-ce docker-ce-cli containerd.io
+                            sudo usermod -aG docker $USER
+                            sudo systemctl enable docker
+                            sudo systemctl start docker
+                            newgrp docker
+                        else
+                            echo "Docker is already installed"
+                        fi
+                        '''
+                    }
+                }
+        }
+
+        
         stage('Build Docker'){
             steps{
                 script{
